### ISSUE TITLE
Incorrect input value for eventvwr_perms

### ISSUE THREAD

**Issue by rdean716** [mitre/microsoft-windows-server-2019-stig-baseline#19]
Hi maintainers,

The input value is currently:

```
  - name: eventvwr_perms
    profile: Windows_Server_2019_STIG
    value:
      - NT AUTHORITY\SYSTEM Allow  ReadAndExecute, Synchronize
      - BUILTIN\Administrators Allow  ReadAndExecute, Synchronize
      - BUILTIN\Users Allow  ReadAndExecute, Synchronize
      - NT SERVICE\TrustedInstaller Allow  FullControl
      - APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES Allow  ReadAndExecute, Synchronize
```

it should include `- APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES Allow  ReadAndExecute, Synchronize` as well.

From a running 2019 host:
```
(get-acl .\eventvwr.exe).AccessToString
NT AUTHORITY\SYSTEM Allow  ReadAndExecute, Synchronize
BUILTIN\Administrators Allow  ReadAndExecute, Synchronize
BUILTIN\Users Allow  ReadAndExecute, Synchronize
NT SERVICE\TrustedInstaller Allow  FullControl
APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES Allow  ReadAndExecute, Synchronize
APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES Allow  ReadAndExecute, Synchronize
```

I will submit a PR, if you're accepting of the modification?
