### ISSUE TITLE
Profile input c_windows_sysvol_perm has a typo

### ISSUE THREAD

**Issue by rdean716** [mitre/microsoft-windows-server-2019-stig-baseline#27]
is currently:
```
 - name: c_windows_sysvol_perm
    desc: "Permissions on folder and file for SYSVOL Directory"
    type: Array
    value:
      - NT AUTHORITY\Authenticated Users:(RX)
      - NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(GR,GE)
      - BUILTIN\Server Operators:(RX)
      - BUILTIN\Server Operators:(OI)(CI)(IO)(GR,GE)
      - BUILTIN\Administrators:(M,WDAC,WO)
      - BUILTIN\Administrators:(OI)(CI)(IO)(F)
      - NT AUTHORITY\SYSTEM:(F)
      - NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
      - BUILTIN\Administrators:(M,WDAC,WO)
      - CREATOR OWNER:(OI)(CI)(IO)(F)

```

Should be:
```
 - name: c_windows_sysvol_perm
    desc: "Permissions on folder and file for SYSVOL Directory"
    type: Array
    value:
      - NT AUTHORITY\Authenticated Users:(RX)
      - NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(GR,GE)
      - BUILTIN\Server Operators:(RX)
      - BUILTIN\Server Operators:(OI)(CI)(IO)(GR,GE)
      - BUILTIN\Administrators:(M,WDAC,WO)
      - BUILTIN\Administrators:(OI)(CI)(IO)(F)
      - NT AUTHORITY\SYSTEM:(F)
      - NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
      - **NT AUTHORITY\SYSTEM:(M,WDAC,WO)**
      - CREATOR OWNER:(OI)(CI)(IO)(F)
```

I will submit a PR.
